import './globals.css'
import Navbar from './component/Navbar'
import ProfilePicture from './component/ProfilePicture'

export const metadata = {
  title: "Hardik's Blogs",
  description: 'Generated by Hardik Sharma',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-deer500/50">
        <Navbar/>
        <ProfilePicture/>
        {children}
        </body>
    </html>
  )
}
